# Linear Equations

## LU Decomposition

In [1]:
from numpy.linalg import solve

A = [
    [1, 2],
    [3, 4]
]

v = [5, 6]

x = solve(A, v)

print(f'{x}')

[-4.   4.5]


## QR Algorithm

In [5]:
from numpy.linalg import eigh, eigvalsh

A = [
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 8]
]

eigenvalues, eigenvectors = eigh(A)

eigenvalues_only = eigvalsh(A)

print(f'{eigenvalues}\n')
print(f'{eigenvectors}\n')
print(f'{eigenvalues_only}')


[-2.7361167  -0.42956121 16.16567792]

[[-0.73135516  0.55193685 -0.40060621]
 [-0.30708641 -0.7909952  -0.52917345]
 [ 0.60894791  0.26399301 -0.74799073]]

[-2.7361167  -0.42956121 16.16567792]


# Non-Linear Equations

## Relaxation Method 

In [51]:
import numpy as np

def f(x):
    return 0.5 * x - 0.5

def g(x):
    return 2 * x + 1

def g_inverse(x):
    return (x - 1) * 0.5

def relaxation(x_guess, func):

    eps = 1
    iters = 0
    max_iters = 30
    while eps > 1e-3 and iters < max_iters:
        x = x_guess
        x_prime = func(x)
        x_second = func(x_prime)
        x_guess = x_second
    
        num = (x_prime - x_second) ** 2
        den = 2 * x_prime - x - x_second

        eps = 0.0 if den == 0 else np.abs(num / den)
        iters += 1

    return x_guess, eps


x_guess = 10
x_sol, err = relaxation(x_guess, f)
print(rf'Convergence succeeds for $f$: {x_sol:.2f} | Error: {err:.2e}')

x_guess2 = 2
x_sol2, err2 = relaxation(x_guess2, g)
print(rf'Convergence fails for $g$: {x_sol2} | Error: {err2:.2e}')

x_guess3 = 2
x_sol3, err3 = relaxation(x_guess3,  g_inverse)
print(rf'Using the inverse $g^{-1}$: {x_sol3:.2f} | Error: {err3:.2e}')




Convergence succeeds for $f$: -1.00 | Error: 6.71e-04
Convergence fails for $g$: 3458764513820540927 | Error: 3.46e+18
Using the inverse $g^-1$: -1.00 | Error: 7.32e-04
