# Linear Equations

## LU Decomposition

In [1]:
from numpy.linalg import solve

A = [
    [1, 2],
    [3, 4]
]

v = [5, 6]

x = solve(A, v)

print(f'{x}')

[-4.   4.5]


## QR Algorithm

In [5]:
from numpy.linalg import eigh, eigvalsh

A = [
    [1, 2, 3],
    [3, 4, 5],
    [6, 7, 8]
]

eigenvalues, eigenvectors = eigh(A)

eigenvalues_only = eigvalsh(A)

print(f'{eigenvalues}\n')
print(f'{eigenvectors}\n')
print(f'{eigenvalues_only}')


[-2.7361167  -0.42956121 16.16567792]

[[-0.73135516  0.55193685 -0.40060621]
 [-0.30708641 -0.7909952  -0.52917345]
 [ 0.60894791  0.26399301 -0.74799073]]

[-2.7361167  -0.42956121 16.16567792]


# Non-Linear Equations

## Relaxation Method 

In [51]:
import numpy as np

def f(x):
    return 0.5 * x - 0.5

def g(x):
    return 2 * x + 1

def g_inverse(x):
    return (x - 1) * 0.5

def relaxation(x_guess, func):

    eps = 1
    iters = 0
    max_iters = 30
    while eps > 1e-3 and iters < max_iters:
        x = x_guess
        x_prime = func(x)
        x_second = func(x_prime)
        x_guess = x_second
    
        num = (x_prime - x_second) ** 2
        den = 2 * x_prime - x - x_second

        eps = 0.0 if den == 0 else np.abs(num / den)
        iters += 1

    return x_guess, eps


x_guess = 10
x_sol, err = relaxation(x_guess, f)
print(rf'Convergence succeeds for $f$: {x_sol:.2f} | Error: {err:.2e}')

x_guess2 = 2
x_sol2, err2 = relaxation(x_guess2, g)
print(rf'Convergence fails for $g$: {x_sol2} | Error: {err2:.2e}')

x_guess3 = 2
x_sol3, err3 = relaxation(x_guess3,  g_inverse)
print(rf'Using the inverse $g^{-1}$: {x_sol3:.2f} | Error: {err3:.2e}')




Convergence succeeds for $f$: -1.00 | Error: 6.71e-04
Convergence fails for $g$: 3458764513820540927 | Error: 3.46e+18
Using the inverse $g^-1$: -1.00 | Error: 7.32e-04


$$ x = y (a + x^2), \quad y = \frac{b}{a+x^2} $$

In [55]:
import numpy as np

a, b = 5, 1
x_true, y_true = b, b / (a+b**2)

x_guess = 10
y_guess = 10

for i in range(20):
    x_new = y_guess * (a + x_guess ** 2)
    y_new = b / (a + x_guess ** 2)
    x_guess, y_guess = x_new, y_new

print(f'x guess: {x_guess}')
print(f'y guess: {y_guess}\n')
print(f'x true: {x_true}')
print(f'y true: {y_true}')


x guess: 0.9998569917138758
y guess: 0.1666793202750407

x true: 1
y true: 0.16666666666666666


## Binary Search Method 

$$ 5 e^{-x} + x -5 = 0 $$

In [16]:
import numpy as np

def f(x):
    return 5 * np.exp(-x) + x - 5

x1, x2 = 1, 10
Delta_initial = np.abs(x1 - x2)
target_accuracy = 1e-6

# If f(x1) and f(x2) have opposite signs
if f(x1) * f(x2) < 0:
    # As long as the distance isn't smaller than accuract
    while np.abs(x1 - x2) >= target_accuracy:
        # Find midpoint
        x_new = 0.5 * (x1 + x2)
        # If f(x1) and f(x_new) have same signs
        if f(x_new) * f(x1) > 0:
            x1 = x_new
        # Otherwise
        else: 
            x2 = x_new
    # After convergence (while loop ends)
    root = 0.5 * (x1 + x2)

# Number of steps required    
N = np.log2(Delta_initial / target_accuracy)

print(f'{root}')
print(f'{N}')


4.965114146471024
23.101493570766486


## Newton's Method

$$ x' = x - \frac{f(x)}{f'(x)}

In [41]:
import numpy as np

def f(x):
    return np.log(x) - np.sin(x)

def f_prime(x):
    return (1 / x) - np.cos(x)

x_guess = 0.1
target = 1e-12

diff = np.inf

while diff > target:
   
    x_new = x_guess - f(x_guess) / f_prime(x_guess)
    diff = np.abs(x_new - x_guess)
    print(f'{x_guess}')
    x_guess = x_new


print(f'Converged solution: {x_guess}')

0.1
0.3667872982658683
1.1262261562930478
2.838405023899215
2.2685127536415144
2.219760079720222
2.21910726891565
2.21910714891375
Converged solution: 2.219107148913746


## Secant Method

In [44]:
import numpy as np

def f(x):
    return np.log(x) - np.sin(x)

x1, x2 = 0.1, 0.2
target = 1e-12

diff = np.inf

while diff > target:
   
    x3 = x2 - f(x2) * ((x2 - x1) / (f(x2) - f(x1)))
    diff = np.abs(x3 - x2)
    print(f'{x2}')
    x1 = x2
    x2 = x3

print(f'Converged solution: {x2}')

0.2
0.504235733935521
1.0591713588220575
2.338152064277259
2.1625609447905045
2.2172728384604627
2.219137255037476
2.219107133344025
2.219107148913614
Converged solution: 2.219107148913746


# Maxima and Minima

## Golden Ratio Method

In [62]:
import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return (x - 5) ** 2 + 2

x1, x4 = 1, 20

z = (1 + np.sqrt(5)) * 0.5 

x2 = x4 - (x4 - x1) / z
x3 = x1 + (x4 - x1) / z

f1, f2, f3, f4 = f(x1), f(x2), f(x3), f(x4)

if (f2 < f1 and f2 < f4) or (f3 < f1 and f3 < f4):
    target = 1e-8
    iters = 0
    while x4 - x1 > target:
        if f2 < f3:
            x4, f4 = x3, f3
            x3, f3 = x2, f2
            x2 = x4 - (x4 - x1) / z
            f2 = f(x2)
        else:
            x1, f1 = x2, f2
            x2, f2 = x3, f3
            x3 = x1 + (x4 - x1) / z
            f3 = f(x3)
 
        iters += 1
    critical_point = 0.5 * (x1 + x4)
    print(f'{critical_point} | Iteration: {iters}')


5.000000015419818 | Iteration: 45


## Gauss-Newton Method

In [88]:
import numpy as np

def f(x):
    return x ** 4

def f_1st(x):
    return 4 * x ** 3

def f_2nd(x):
    return 12 * x ** 2

x = 10
err = 1e-12
it = 0
diff = np.inf

while diff > err:
    x_new = x - f_1st(x) / f_2nd(x)
    diff = np.abs(x_new - x)
    x = x_new
    it += 1

print(f'{x}')
print(f'{it}')



1.397455827091953e-12
73


In [93]:
import numpy as np

def f(x):
    return x ** 4

def f_1st(x):
    return 4 * x ** 3

x = 5
err = 1e-6
it = 0
diff = np.inf

gamma = 0.0001
while diff > err:
    x_new = x - gamma * f_1st(x)
    diff = np.abs(x_new - x)
    x = x_new
    it += 1

print(f'{x}')
print(f'{it}')

0.1357189050646496
67807
